#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Checkpoint saving/loading."""
from __future__ import annotations
from pathlib import Path
from typing import Any, Dict
import torch

FORMAT_VERSION = "RB_AFL_CKPT_V01"


def save_checkpoint(path: str | Path, generator, discriminator, opt_g, opt_d, epoch: int, best_val: float, config: Dict[str, Any], extra: Dict[str, Any] | None = None) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    ckpt = {
        "format_version": FORMAT_VERSION,
        "epoch": int(epoch),
        "best_val": float(best_val),
        "generator": generator.state_dict(),
        "discriminator": None if discriminator is None else discriminator.state_dict(),
        "opt_g": None if opt_g is None else opt_g.state_dict(),
        "opt_d": None if opt_d is None else opt_d.state_dict(),
        "config": dict(config),
        "channel_names": list(config.get("channels", ["occ", "dist", "orient", "density"])),
        "grid_size": int(config.get("grid_size", 256)),
        "input_shape": [len(config.get("channels", ["occ", "dist", "orient", "density"])), int(config.get("grid_size", 256)), int(config.get("grid_size", 256))],
        "feat_dim": int(config.get("feat_dim", 256)),
        "generator_name": str(config.get("generator", "cnn_baseline")),
        "discriminator_name": str(config.get("discriminator", "fc")),
    }
    if extra:
        ckpt.update(extra)
    torch.save(ckpt, p)


def load_checkpoint(path: str | Path, map_location: str = "cpu") -> Dict[str, Any]:
    """Load a trusted local RB-AFL checkpoint.

    V08 explicitly passes weights_only=False on PyTorch versions that support it,
    removing the repeated FutureWarning while preserving the RB-AFL checkpoint
    format with metadata/config plus state_dict objects. Only load checkpoints
    generated by this project or otherwise trusted.
    """
    p = Path(path)
    if not p.is_file():
        raise FileNotFoundError(str(p))
    try:
        ckpt = torch.load(p, map_location=map_location, weights_only=False)
    except TypeError:
        ckpt = torch.load(p, map_location=map_location)
    if not isinstance(ckpt, dict):
        raise TypeError(f"Checkpoint must be a dict, got {type(ckpt)!r}")
    if "generator" not in ckpt:
        raise KeyError("Checkpoint missing 'generator' state_dict")
    return ckpt
